print('programa que determina el tipo de triángulo por los lados')
x=float(input('introduzca valor de el primer lado: '))
y=float(input('introduzca valor de el segundo lado: '))
z=float(input('introduzca valor de el tercer lado: '))
a = int(input('Introduce el valor de a: ')
